# Generated by Django 5.2.17 on 2026-09-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_auth_version_accountactionauthorization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
