# Generated by Django 5.2.17 on 2026-09-21 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('companies', '0007_companybookingsettings_whatsapp_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='origin',
            field=models.CharField(choices=[('CUSTOMER', 'Cliente'), ('ADMIN', 'Administrador'), ('PROFESSIONAL', 'Profissional')], default='CUSTOMER', max_length=16),
        ),
        migrations.AddField(
            model_name='appointment',
            name='outcome',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Concluído'), ('NO_SHOW', 'Não compareceu')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='outcome_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='outcome_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_appointment_outcomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.TextField()),
                ('endpoint_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('p256dh', models.CharField(max_length=256)),
                ('auth', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('permission_source', models.CharField(default='BOOKING_REMINDERS', max_length=32)),
                ('consented_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_credential', to='bookings.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppointmentOutcomeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('COMPLETED', 'Concluído'), ('NO_SHOW', 'Não compareceu')], max_length=16)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_outcome_events', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_events', to='bookings.appointment')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['appointment', 'created_at'], name='appointment_outcome_event_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BOOKING_CONFIRMED', 'Agendamento confirmado'), ('BOOKING_REMINDER', 'Lembrete de agendamento'), ('BOOKING_RESCHEDULED', 'Agendamento reagendado'), ('BOOKING_CANCELLED', 'Agendamento cancelado'), ('REVIEW_REQUEST', 'Solicitação de avaliação')], max_length=32)),
                ('scheduled_for', models.DateTimeField()),
                ('state', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('FAILED', 'Falhou')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='bookings.appointment')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'scheduled_for'], name='notification_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'kind', 'scheduled_for'), name='unique_booking_notification_event')],
            },
        ),
        migrations.CreateModel(
            name='BookingPushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_links', to='bookings.appointment')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_links', to='bookings.pushsubscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appointment', 'subscription'), name='unique_booking_push_subscription')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('company_response', models.TextField(blank=True, max_length=2000)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='bookings.appointment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'created_at'], name='review_company_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_range')],
            },
        ),
    ]
