# Generated by Django 5.2.17 on 2026-09-26 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_appointment_origin_appointment_outcome_and_more'),
        ('companies', '0008_companyunit'),
        ('professionals', '0004_professional_units_workschedule_unit'),
        ('services', '0004_service_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='appointment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='companies.companyunit'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(condition=models.Q(('outcome__isnull', True), ('status', 'WAITING_CONFIRMATION')), fields=['starts_at'], name='appointment_pending_due_idx'),
        ),
    ]
