# Generated by Django 5.2.17 on 2026-09-10 20:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='companies.company')),
                ('services', models.ManyToManyField(blank=True, related_name='professionals', to='services.service')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='professionals.professional')),
            ],
            options={
                'ordering': ('weekday', 'starts_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='professional',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_professional_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='schedule_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.UniqueConstraint(fields=('professional', 'weekday', 'starts_at', 'ends_at'), name='unique_professional_schedule'),
        ),
    ]
