# Generated by Django 5.2.17 on 2026-09-26 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companyunit'),
        ('professionals', '0003_professional_access_active_professional_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='companies.companyunit'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_schedules', to='companies.companyunit'),
        ),
    ]
