import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState, type FormEvent } from 'react'
import { api, apiErrorMessage } from '../../api/client'
import { Button, EmptyState, Field, LoadingState, Notice, SelectField, TextAreaField } from '../../components/ui'
import { formatDateTime } from '../../lib/format'
import type { Feedback, Paginated } from '../../types/api'
import { categories, downloadAttachment, origins, priorities, statuses } from '../FeedbackPage'

type Filters = { category: string; status: string; priority: string; user_type: string; company: string; search: string; ordering: string }
const initial: Filters = { category: '', status: '', priority: '', user_type: '', company: '', search: '', ordering: '-created_at' }

function Filter({ label, value, options, onChange }: { label: string; value: string; options: Record<string, string>; onChange: (value: string) => void }) {
  return <SelectField label={label} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Todos</option>{Object.entries(options).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</SelectField>
}

export default function PlatformFeedbackPage() {
  const client = useQueryClient()
  const [filters, setFilters] = useState<Filters>(initial)
  const [page, setPage] = useState(1)
  const [selected, setSelected] = useState<string | null>(null)
  const [message, setMessage] = useState('')
  const [internal, setInternal] = useState(false)
  const [downloadError, setDownloadError] = useState('')
  const setFilter = (key: keyof Filters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1) }
  const params = new URLSearchParams({ page: String(page) })
  Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, value) })
  const list = useQuery({ queryKey: ['platform-feedback', params.toString()], queryFn: () => api.get<Paginated<Feedback>>(`/platform/feedback/?${params}`) })
  const detail = useQuery({ queryKey: ['platform-feedback-detail', selected], queryFn: () => api.get<Feedback>(`/platform/feedback/${selected}/`), enabled: Boolean(selected) })
  const update = useMutation({ mutationFn: (payload: Partial<Pick<Feedback, 'status' | 'priority'>>) => api.patch<Feedback>(`/platform/feedback/${selected}/`, payload), onSuccess: (data) => { client.setQueryData(['platform-feedback-detail', selected], data); client.invalidateQueries({ queryKey: ['platform-feedback'] }) } })
  const reply = useMutation({ mutationFn: () => api.post(`/platform/feedback/${selected}/reply/`, { message, is_internal: internal }), onSuccess: () => { setMessage(''); client.invalidateQueries({ queryKey: ['platform-feedback-detail', selected] }) } })
  const submitReply = (event: FormEvent) => { event.preventDefault(); if (message.trim()) reply.mutate() }
  const item = detail.data
  return <div className="min-w-0"><header className="mb-6"><h1 className="page-title">Central de feedback</h1><p className="muted mt-2 text-sm">{list.data?.count ?? '—'} feedbacks encontrados</p></header>
    <section className="panel mb-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Field label="Pesquisar" value={filters.search} onChange={(event) => setFilter('search', event.target.value)} placeholder="Título, mensagem ou usuário" /><Filter label="Categoria" value={filters.category} options={categories} onChange={(value) => setFilter('category', value)} /><Filter label="Status" value={filters.status} options={statuses} onChange={(value) => setFilter('status', value)} /><Filter label="Prioridade" value={filters.priority} options={priorities} onChange={(value) => setFilter('priority', value)} /><Filter label="Origem" value={filters.user_type} options={origins} onChange={(value) => setFilter('user_type', value)} /><Field label="Empresa" value={filters.company} onChange={(event) => setFilter('company', event.target.value)} /><SelectField label="Ordenar por" value={filters.ordering} onChange={(event) => setFilter('ordering', event.target.value)}><option value="-created_at">Mais recentes</option><option value="created_at">Mais antigos</option><option value="-updated_at">Atualizados recentemente</option><option value="priority">Prioridade</option></SelectField></div></section>
    {list.isPending && <LoadingState />}{list.isError && <Notice>{apiErrorMessage(list.error)}</Notice>}{list.data?.results.length === 0 && <EmptyState title="Nenhum feedback encontrado" description="Ajuste os filtros ou aguarde novas mensagens." />}
    {list.data && list.data.results.length > 0 && <div className="table-wrap"><table className="data-table responsive-table"><thead><tr><th>ID</th><th>Título</th><th>Categoria</th><th>Usuário</th><th>Empresa</th><th>Status</th><th>Prioridade</th><th>Data</th></tr></thead><tbody>{list.data.results.map((feedback) => <tr key={feedback.id}><td data-label="ID"><button className="font-semibold text-[#087cf0] underline" onClick={() => { setSelected(feedback.id); setDownloadError('') }}>{feedback.public_id}</button></td><td data-label="Título" className="max-w-64 break-words">{feedback.title}</td><td data-label="Categoria">{categories[feedback.category]}</td><td data-label="Usuário">{feedback.user_name || feedback.user_email}</td><td data-label="Empresa">{feedback.company_name || '—'}</td><td data-label="Status">{statuses[feedback.status]}</td><td data-label="Prioridade">{priorities[feedback.priority]}</td><td data-label="Data">{formatDateTime(feedback.created_at)}</td></tr>)}</tbody></table></div>}
    {list.data && list.data.count > 50 && <nav aria-label="Paginação" className="mt-5 flex items-center gap-3"><Button variant="secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Anterior</Button><span>Página {page}</span><Button variant="secondary" disabled={!list.data.next} onClick={() => setPage(page + 1)}>Próxima</Button></nav>}
    {selected && <section className="panel mt-6 min-w-0"><Button variant="ghost" onClick={() => { setSelected(null); update.reset() }}>Fechar detalhes</Button>{detail.isPending && <LoadingState />}{detail.isError && <Notice>{apiErrorMessage(detail.error)}</Notice>}{item && <><p className="mt-5 text-sm font-semibold text-[#52658a]">{item.public_id} · {formatDateTime(item.created_at)}</p><h2 className="mt-2 break-words text-xl font-semibold">{item.title}</h2><p className="mt-4 whitespace-pre-wrap break-words">{item.description}</p><dl className="mt-6 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3">{[['Usuário', `${item.user_name} (${item.user_email})`], ['Origem', origins[item.user_type]], ['Empresa', item.company_name], ['Profissional', item.professional_name], ['Categoria', categories[item.category]], ['Página', item.page_url], ['Navegador', [item.browser, item.browser_version].filter(Boolean).join(' ')], ['Sistema operacional', item.operating_system], ['Dispositivo', item.device_type], ['Versão da aplicação', item.app_version]].map(([label, value]) => <div key={label} className="min-w-0"><dt className="text-[#52658a]">{label}</dt><dd className="break-words font-medium">{value || '—'}</dd></div>)}</dl>
      <div className="mt-6 grid gap-4 sm:grid-cols-2"><SelectField label="Status" value={item.status} disabled={update.isPending} onChange={(event) => update.mutate({ status: event.target.value as Feedback['status'] })}>{Object.entries(statuses).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</SelectField><SelectField label="Prioridade" value={item.priority} disabled={update.isPending} onChange={(event) => update.mutate({ priority: event.target.value as Feedback['priority'] })}>{Object.entries(priorities).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</SelectField></div>{update.isError && <Notice>{apiErrorMessage(update.error)}</Notice>}
      <h3 className="mt-7 font-semibold">Anexos</h3>{item.attachments.length ? item.attachments.map((file) => <Button key={file.id} variant="ghost" onClick={() => void downloadAttachment(`/platform/feedback/${item.id}/attachments/${file.id}/download/`, file.original_filename).catch((error) => setDownloadError(apiErrorMessage(error)))}>{file.original_filename}</Button>) : <p className="text-sm text-[#52658a]">Nenhum anexo.</p>}{downloadError && <Notice>{downloadError}</Notice>}
      <h3 className="mt-7 font-semibold">Respostas e comentários internos</h3>{item.replies.length ? item.replies.map((entry) => <article key={entry.id} className="mt-3 rounded-xl border border-[#d8e5f4] p-4"><p className="text-xs text-[#52658a]">{entry.is_internal ? 'Comentário interno' : 'Resposta ao usuário'} · {entry.author_name} · {formatDateTime(entry.created_at)}</p><p className="mt-2 whitespace-pre-wrap break-words">{entry.message}</p></article>) : <p className="mt-2 text-sm text-[#52658a]">Nenhuma resposta ainda.</p>}
      <form className="mt-6 grid gap-4" onSubmit={submitReply}><SelectField label="Tipo de mensagem" value={internal ? 'internal' : 'public'} onChange={(event) => setInternal(event.target.value === 'internal')}><option value="public">Resposta ao usuário</option><option value="internal">Comentário interno</option></SelectField><TextAreaField label="Mensagem" value={message} onChange={(event) => setMessage(event.target.value)} maxLength={5000} required />{reply.isError && <Notice>{apiErrorMessage(reply.error)}</Notice>}<Button loading={reply.isPending}>Enviar resposta</Button></form></>}</section>}
  </div>
}
