# Generated by Django 5.2.17 on 2026-09-10 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companybookingsettings_booking_slot_interval_range_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', datetime.timedelta(seconds=300)), ('duration__lte', datetime.timedelta(days=1))), name='service_duration_range'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0), ('price__isnull', True), _connector='OR'), name='service_nonnegative_price'),
        ),
    ]
