# Generated by Django 5.2.17 on 2026-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companyunit'),
        ('services', '0003_service_slot_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='services', to='companies.companyunit'),
        ),
    ]
