# Generated by Django 5.2.17 on 2026-09-26 22:45

from django.db import migrations


def scope_legacy_services(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    Unit = apps.get_model("companies", "CompanyUnit")
    Appointment = apps.get_model("bookings", "Appointment")
    Professional = apps.get_model("professionals", "Professional")
    memberships = Service.units.through
    database = schema_editor.connection.alias
    for service in Service.objects.using(database).filter(units__isnull=True).iterator(chunk_size=500):
        # Preserve historical/future bookings without offering the catalog in every branch.
        ids = set(Appointment.objects.using(database).filter(
            service_id=service.pk, company_id=service.company_id, unit__company_id=service.company_id,
        ).values_list("unit_id", flat=True))
        primary = Unit.objects.using(database).filter(company_id=service.company_id, is_primary=True).first()
        if primary:
            ids.add(primary.pk)
        ids.update(Professional.objects.using(database).filter(
            company_id=service.company_id, services=service, units__company_id=service.company_id,
        ).values_list("units__pk", flat=True))
        memberships.objects.using(database).bulk_create([
            memberships(service_id=service.pk, companyunit_id=pk) for pk in ids
        ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_units'),
        ('companies', '0009_backfill_units'),
    ]

    operations = [
        migrations.RunPython(scope_legacy_services, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='service',
            name='unique_service_name_per_company',
        ),
    ]
