# Generated by Django 5.2.17 on 2026-09-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='schedule_valid_weekday'),
        ),
    ]
