# Generated by Django 5.2.17 on 2026-09-21 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companybookingsettings_whatsapp_messages'),
        ('professionals', '0002_workschedule_schedule_valid_weekday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='access_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfessionalAccessInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_invites', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_professional_invites', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_invites', to='professionals.professional')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['company', 'professional', 'expires_at'], name='professional_invite_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalUnavailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('kind', models.CharField(choices=[('HOURS', 'Bloqueio de horas'), ('DAY_OFF', 'Folga'), ('VACATION', 'Férias'), ('APPOINTMENT', 'Compromisso'), ('OTHER', 'Outra indisponibilidade')], default='HOURS', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_unavailabilities', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='professionals.professional')),
            ],
            options={
                'ordering': ('starts_at',),
                'indexes': [models.Index(fields=['company', 'professional', 'starts_at', 'ends_at'], name='unavailability_period_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__lt', models.F('ends_at'))), name='unavailability_start_before_end')],
            },
        ),
    ]
