# Generated by Django 5.2.17 on 2026-09-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_alter_professionalaccessinvite_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='professional',
            name='unique_professional_name_per_company',
        ),
    ]
