# Generated by Django 5.2.17 on 2026-09-10 20:42

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tax_identifier', models.CharField(blank=True, max_length=14)),
                ('whatsapp', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('niche', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('SUSPENDED', 'Suspensa')], default='ACTIVE', max_length=10)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owned_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CompanyBookingSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_interval', models.DurationField(default=datetime.timedelta(seconds=1800), validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=300))])),
                ('late_tolerance', models.DurationField(default=datetime.timedelta(seconds=600), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('minimum_change_notice', models.DurationField(default=datetime.timedelta(days=1), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_identifier', ''), _negated=True), fields=('tax_identifier',), name='unique_nonempty_company_tax_identifier'),
        ),
    ]
