# Generated by Django 5.2.17 on 2026-09-10 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companybookingsettings',
            constraint=models.CheckConstraint(condition=models.Q(('slot_interval__gte', datetime.timedelta(seconds=300)), ('slot_interval__lte', datetime.timedelta(days=1))), name='booking_slot_interval_range'),
        ),
        migrations.AddConstraint(
            model_name='companybookingsettings',
            constraint=models.CheckConstraint(condition=models.Q(('late_tolerance__gte', datetime.timedelta(0)), ('late_tolerance__lte', datetime.timedelta(days=1))), name='booking_late_tolerance_range'),
        ),
        migrations.AddConstraint(
            model_name='companybookingsettings',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_change_notice__gte', datetime.timedelta(0)), ('minimum_change_notice__lte', datetime.timedelta(days=365))), name='booking_change_notice_range'),
        ),
    ]
