# Generated by Django 5.2.17 on 2026-09-14 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='CompanyViewVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visitor_digest', models.CharField(editable=False, max_length=64)),
                ('last_viewed_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('Barbershop', 'Barbearia'), ('Salon', 'Salão de beleza'), ('Aesthetics clinic', 'Clínica de estética'), ('Clinic', 'Clínica'), ('Dental clinic', 'Clínica odontológica'), ('Physiotherapy', 'Fisioterapia'), ('Pilates studio', 'Estúdio de pilates'), ('Gym', 'Academia'), ('Spa', 'Spa'), ('Consulting', 'Consultoria'), ('Other', 'Outro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='niche',
            field=models.CharField(choices=[('Beauty', 'Beleza'), ('Health', 'Saúde'), ('Wellness', 'Bem-estar'), ('Fitness', 'Atividade física'), ('Education', 'Educação'), ('Pets', 'Cuidados para pets'), ('Other', 'Outros')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status', 'state', 'city'], name='company_discovery_place_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status', 'niche', 'business_type'], name='company_discovery_type_idx'),
        ),
        migrations.AddField(
            model_name='companydailymetric',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyviewvisitor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_visitors', to='companies.company'),
        ),
        migrations.AddConstraint(
            model_name='companydailymetric',
            constraint=models.UniqueConstraint(fields=('company', 'date'), name='unique_company_daily_metric'),
        ),
        migrations.AddIndex(
            model_name='companyviewvisitor',
            index=models.Index(fields=['company', 'date'], name='company_visitor_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyviewvisitor',
            constraint=models.UniqueConstraint(fields=('company', 'date', 'visitor_digest'), name='unique_company_daily_visitor'),
        ),
    ]
