# Generated by Django 5.2.17 on 2026-09-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companydailymetric_companyviewvisitor_company_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('Barbershop', 'Barbearia'), ('Salon', 'Salão de beleza'), ('Aesthetics clinic', 'Clínica de estética'), ('Clinic', 'Clínica'), ('Medical office', 'Consultório'), ('Dental clinic', 'Clínica odontológica'), ('Physiotherapy', 'Fisioterapia'), ('Pilates studio', 'Estúdio de pilates'), ('Gym', 'Academia'), ('Spa', 'Spa'), ('Manicure', 'Manicure'), ('Auto repair', 'Oficina'), ('Auto detailing', 'Estética automotiva'), ('Pet care', 'Pet shop e cuidados'), ('Consulting', 'Consultoria'), ('Other', 'Outro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='niche',
            field=models.CharField(choices=[('Beauty', 'Beleza'), ('Health', 'Saúde'), ('Wellness', 'Bem-estar'), ('Fitness', 'Atividade física'), ('Automotive', 'Automotivo'), ('Education', 'Educação'), ('Pets', 'Cuidados para pets'), ('Other', 'Outros')], max_length=100),
        ),
    ]
