# Generated by Django 5.2.17 on 2026-09-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationkey',
            options={'ordering': ('-created_at',)},
        ),
    ]
