# Generated by Django 5.2.17 on 2026-09-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_core', '0004_enable_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalacceptance',
            name='context',
            field=models.CharField(choices=[('CUSTOMER_REGISTER', 'Cadastro de cliente'), ('COMPANY_REGISTER', 'Cadastro de empresa'), ('ANONYMOUS_BOOKING', 'Agendamento anônimo'), ('EXISTING_USER_REACCEPTANCE', 'Novo aceite de usuário existente'), ('PROFESSIONAL_REGISTER', 'Cadastro de profissional')], max_length=40),
        ),
    ]
