# Generated by Django 5.2.17 on 2026-09-16 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='AccountActionAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('PASSWORD_CHANGE', 'Alteração de senha'), ('EMAIL_CHANGE', 'Alteração de e-mail')], max_length=32)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('email_candidate', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountSecurityRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_digest', models.CharField(max_length=64)),
                ('endpoint', models.CharField(max_length=64)),
                ('purpose', models.CharField(blank=True, max_length=32)),
                ('window_started_at', models.DateTimeField()),
                ('hits', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['window_started_at'], name='account_rate_window_idx')],
                'constraints': [models.UniqueConstraint(fields=('key_digest', 'endpoint', 'purpose', 'window_started_at'), name='unique_account_security_rate_window')],
            },
        ),
        migrations.CreateModel(
            name='AccountVerificationChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('PASSWORD_CHANGE', 'Alteração de senha'), ('EMAIL_CHANGE_CURRENT', 'Confirmação do e-mail atual'), ('EMAIL_CHANGE_NEW', 'Confirmação do novo e-mail')], max_length=32)),
                ('code_hash', models.CharField(editable=False, max_length=128)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('request_ip_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('request_user_agent', models.CharField(blank=True, editable=False, max_length=255)),
                ('authorization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='accounts.accountactionauthorization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='accountactionauthorization',
            index=models.Index(fields=['user', 'purpose', 'expires_at'], name='account_auth_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='accountverificationchallenge',
            index=models.Index(fields=['user', 'purpose', 'expires_at'], name='account_otp_lookup_idx'),
        ),
    ]
