import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { format } from 'date-fns'
import { useState, type FormEvent } from 'react'
import { api, apiErrorMessage } from '../../api/client'
import { Button, Dialog, EmptyState, Field, LoadingState, Notice, SelectField, TextAreaField } from '../../components/ui'
import { formatDateTime } from '../../lib/format'
import type { CompanyReport, Paginated, Professional, Review, Unavailability } from '../../types/api'

const today = () => format(new Date(), 'yyyy-MM-dd')
const monthStart = () => format(new Date(new Date().getFullYear(), new Date().getMonth(), 1), 'yyyy-MM-dd')

export function ReportsPage() {
  const [period, setPeriod] = useState({ from: monthStart(), to: today() })
  const query = useQuery({ queryKey: ['reports', period], queryFn: () => api.get<CompanyReport>(`/company/reports/?date_from=${period.from}&date_to=${period.to}`) })
  return <Page title="Relatórios" description="Histórico operacional, sem estimativas financeiras."><div className="mb-5 grid max-w-xl gap-3 sm:grid-cols-2"><Field label="De" type="date" value={period.from} onChange={(event) => setPeriod({ ...period, from: event.target.value })} /><Field label="Até" type="date" value={period.to} onChange={(event) => setPeriod({ ...period, to: event.target.value })} /></div>{query.isPending && <LoadingState />}{query.isError && <Notice>{apiErrorMessage(query.error)}</Notice>}{query.data && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{[['Total', query.data.total], ['Concluídos', query.data.completed], ['Cancelados', query.data.cancelled], ['Faltas', query.data.no_show], ['Comparecimento', `${query.data.attendance_rate}%`], ['Taxa de não comparecimento', `${query.data.no_show_rate}%`]].map(([label, value]) => <div className="panel" key={label}><p className="text-sm text-[#7182a8]">{label}</p><strong className="mt-2 block text-2xl">{value}</strong></div>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><Ranking title="Serviços mais agendados" items={query.data.services.map((item) => [item.service__name, item.total])} /><Ranking title="Profissionais com mais atendimentos" items={query.data.professionals.map((item) => [item.professional__name, item.total])} /><Ranking title="Horários de maior movimento" items={query.data.hours.map((item) => [`${item.value}:00`, item.total])} /><Ranking title="Clientes recorrentes" items={query.data.recurring_customers.map((item) => [item.customer_name, item.total])} /></div></>}</Page>
}

export function UnavailabilitiesPage() {
  const client = useQueryClient(); const [open, setOpen] = useState(false)
  const periods = useQuery({ queryKey: ['unavailabilities'], queryFn: () => api.get<Paginated<Unavailability>>('/company/unavailabilities/') })
  const professionals = useQuery({ queryKey: ['professionals'], queryFn: () => api.get<Paginated<Professional>>('/company/professionals/') })
  const create = useMutation({ mutationFn: (payload: object) => api.post('/company/unavailabilities/', payload), onSuccess: () => { setOpen(false); client.invalidateQueries({ queryKey: ['unavailabilities'] }) } })
  const remove = useMutation({ mutationFn: (id: string) => api.delete(`/company/unavailabilities/${id}/`), onSuccess: () => client.invalidateQueries({ queryKey: ['unavailabilities'] }) })
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ professional: data.get('professional'), starts_at: new Date(String(data.get('starts_at'))).toISOString(), ends_at: new Date(String(data.get('ends_at'))).toISOString(), kind: data.get('kind'), reason: data.get('reason'), allow_conflicts: data.get('allow_conflicts') === 'on' }) }
  return <Page title="Indisponibilidades" description="Bloqueios pontuais sem alterar a jornada semanal." action={<Button onClick={() => setOpen(true)}>Novo bloqueio</Button>}>{periods.isPending && <LoadingState />}{periods.isError && <Notice>{apiErrorMessage(periods.error)}</Notice>}{periods.data?.results.length === 0 && <EmptyState title="Nenhum bloqueio" description="Férias, folgas e compromissos aparecerão aqui." />}{periods.data && <div className="grid gap-3">{periods.data.results.map((item) => <article className="surface flex flex-wrap items-center justify-between gap-3 p-4" key={item.id}><div><strong>{formatDateTime(item.starts_at)} – {formatDateTime(item.ends_at)}</strong><p className="text-sm text-[#7182a8]">{item.reason || item.kind}</p></div><Button variant="danger" onClick={() => remove.mutate(item.id)}>Remover</Button></article>)}</div>}<Dialog open={open} title="Novo bloqueio" onClose={() => setOpen(false)}><form className="grid gap-4" onSubmit={submit}><SelectField label="Profissional" name="professional" required><option value="">Selecione</option>{professionals.data?.results.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectField><div className="grid gap-3 sm:grid-cols-2"><Field label="Início" name="starts_at" type="datetime-local" required /><Field label="Fim" name="ends_at" type="datetime-local" required /></div><SelectField label="Tipo" name="kind"><option value="HOURS">Bloqueio de horas</option><option value="DAY_OFF">Folga</option><option value="VACATION">Férias</option><option value="APPOINTMENT">Compromisso</option><option value="OTHER">Outro</option></SelectField><TextAreaField label="Motivo opcional" name="reason" maxLength={500} /><label className="flex gap-2 text-sm"><input type="checkbox" name="allow_conflicts" /> Estou ciente e quero criar mesmo se houver agendamentos no período.</label>{create.isError && <Notice>{apiErrorMessage(create.error)}</Notice>}<Button loading={create.isPending}>Criar bloqueio</Button></form></Dialog></Page>
}

export function ReviewsPage() {
  const client = useQueryClient(); const [selected, setSelected] = useState<Review | null>(null)
  const query = useQuery({ queryKey: ['reviews'], queryFn: () => api.get<Paginated<Review>>('/company/reviews/') })
  const respond = useMutation({ mutationFn: ({ id, response }: { id: string; response: string }) => api.post(`/company/reviews/${id}/respond/`, { company_response: response }), onSuccess: () => { setSelected(null); client.invalidateQueries({ queryKey: ['reviews'] }) } })
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); respond.mutate({ id: selected!.id, response: String(new FormData(event.currentTarget).get('response') || '') }) }
  return <Page title="Avaliações" description="Somente avaliações vinculadas a atendimentos concluídos.">{query.isPending && <LoadingState />}{query.isError && <Notice>{apiErrorMessage(query.error)}</Notice>}{query.data?.results.length === 0 && <EmptyState title="Nenhuma avaliação" description="Avaliações verificadas aparecerão aqui." />}{query.data && <div className="grid gap-3">{query.data.results.map((item) => <article className="surface p-4" key={item.id}><div className="flex flex-wrap justify-between gap-3"><strong>{'★'.repeat(item.rating)} · Atendimento verificado</strong><Button variant="secondary" onClick={() => setSelected(item)}>Responder</Button></div><p className="mt-2 text-sm">{item.comment || 'Sem comentário.'}</p>{item.company_response && <p className="mt-3 border-l-2 border-[#087cf0] pl-3 text-sm">Resposta: {item.company_response}</p>}</article>)}</div>}<Dialog open={Boolean(selected)} title="Responder avaliação" onClose={() => setSelected(null)}><form className="grid gap-4" onSubmit={submit}><TextAreaField label="Resposta" name="response" defaultValue={selected?.company_response} maxLength={2000} />{respond.isError && <Notice>{apiErrorMessage(respond.error)}</Notice>}<Button loading={respond.isPending}>Salvar resposta</Button></form></Dialog></Page>
}

function Ranking({ title, items }: { title: string; items: Array<[string, number]> }) { return <section className="panel"><h2 className="font-semibold">{title}</h2><ol className="mt-3 space-y-2">{items.length ? items.map(([label, total]) => <li className="flex justify-between gap-3 text-sm" key={label}><span>{label}</span><strong>{total}</strong></li>) : <li className="text-sm text-[#7182a8]">Sem dados no período.</li>}</ol></section> }
function Page({ title, description, action, children }: { title: string; description: string; action?: React.ReactNode; children: React.ReactNode }) { return <div><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="page-title">{title}</h1><p className="muted mt-2 text-sm">{description}</p></div>{action}</header>{children}</div> }
