import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { addDays, format, isSameDay, isTomorrow, parseISO } from 'date-fns'
import { ptBR } from 'date-fns/locale'
import { LuArrowLeft as ArrowLeft, LuCheck as Check, LuExternalLink as ExternalLink, LuImageUp as ImageUp, LuPencil as Pencil, LuPlus as Plus, LuSearch as Search, LuTrash2 as Trash2 } from 'react-icons/lu'
import { useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router'
import { api, apiErrorMessage, apiFieldErrors } from '../../api/client'
import { CityAutocomplete } from '../../components/CityAutocomplete'
import { ProfileAvatar } from '../../components/ProfileAvatar'
import { StatusBadge } from '../../components/StatusBadge'
import { Button, Dialog, EmptyState, Field, LoadingState, Notice, SelectField, TextAreaField, validateForm } from '../../components/ui'
import { durationMinutes, durationToFriendlyUnit, formatDateTime, formatMoney, formatTime, friendlyUnitToDuration, minutesToDuration, whatsappUrl, type FriendlyDurationUnit } from '../../lib/format'
import { safeImageUrl } from '../../lib/media'
import type { Appointment, BookingSettings, Company, CompanyCustomer, Paginated, Professional, PublicPlatformConfig, Service, WorkSchedule } from '../../types/api'

const list = <T,>(path: string) => api.get<Paginated<T>>(path)
async function listAll<T>(path: string): Promise<Paginated<T>> {
  const results: T[] = []
  let page = 1
  let response: Paginated<T>
  do {
    response = await list<T>(`${path}${path.includes('?') ? '&' : '?'}page=${page}`)
    results.push(...response.results)
    page += 1
  } while (response.next)
  return { count: results.length, next: null, previous: null, results }
}
const today = () => format(new Date(), 'yyyy-MM-dd')

export function DashboardPage() {
  const appointments = useQuery({ queryKey: ['appointments', 'upcoming'], queryFn: () => listAll<Appointment>(`/company/appointments/?date_from=${today()}&page_size=200`) })
  const waitingAppointments = useQuery({ queryKey: ['appointments', 'waiting'], queryFn: () => listAll<Appointment>('/company/appointments/?status=WAITING_CONFIRMATION&page_size=200') })
  const services = useQuery({ queryKey: ['services'], queryFn: () => list<Service>('/company/services/') })
  const professionals = useQuery({ queryKey: ['professionals'], queryFn: () => list<Professional>('/company/professionals/') })
  if (appointments.isPending || waitingAppointments.isPending || services.isPending || professionals.isPending) return <LoadingState label="Carregando visão geral" />
  const error = appointments.error || waitingAppointments.error || services.error || professionals.error
  if (error) return <Notice>{apiErrorMessage(error)}</Notice>
  const now = new Date()
  const upcoming = (appointments.data?.results || []).filter((item) => item.status !== 'CANCELLED' && new Date(item.starts_at) >= now).sort((a, b) => a.starts_at.localeCompare(b.starts_at))
  const todayItems = upcoming.filter((item) => isSameDay(parseISO(item.starts_at), now))
  const waiting = (waitingAppointments.data?.results || []).slice().sort((a, b) => {
    const aTime = new Date(a.starts_at).getTime()
    const bTime = new Date(b.starts_at).getTime()
    const aPast = aTime < now.getTime()
    const bPast = bTime < now.getTime()
    if (aPast !== bPast) return aPast ? 1 : -1
    return aPast ? bTime - aTime : aTime - bTime
  })
  return <Page title="Visão geral" description={`Operação de ${format(new Date(), "EEEE, d 'de' MMMM", { locale: ptBR })}.`}>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Agendamentos hoje" value={todayItems.length} /><Metric label="Aguardando confirmação" value={waiting.length} /><Metric label="Serviços ativos" value={services.data?.results.filter((item) => item.is_active).length || 0} /><Metric label="Profissionais ativos" value={professionals.data?.results.filter((item) => item.is_active).length || 0} /></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-2">
      <section><h2 className="text-lg font-semibold">Próximos agendamentos</h2>{upcoming.length ? <UpcomingAppointments items={upcoming} /> : <div className="mt-3"><EmptyState title="Agenda livre" description="Nenhum próximo agendamento foi encontrado." /></div>}</section>
      <section><h2 className="text-lg font-semibold">Aguardando confirmação</h2>{waiting.length ? <div className="mt-3 max-h-[32rem] overflow-y-auto rounded-xl border border-[#d8e5f4]"><AppointmentTable items={waiting} compact /></div> : <div className="mt-3"><EmptyState title="Nada pendente" description="Não há agendamentos aguardando confirmação." /></div>}</section>
    </div>
  </Page>
}

function UpcomingAppointments({ items }: { items: Appointment[] }) {
  const groups = new Map<string, Appointment[]>()
  for (const item of items) {
    const key = format(parseISO(item.starts_at), 'yyyy-MM-dd')
    groups.set(key, [...(groups.get(key) || []), item])
  }
  return <div className="mt-3 max-h-[32rem] space-y-4 overflow-y-auto rounded-xl border border-[#d8e5f4] bg-white p-4">{[...groups].map(([date, appointments]) => {
    const parsed = new Date(`${date}T12:00:00`)
    const label = isSameDay(parsed, new Date()) ? 'Hoje' : isTomorrow(parsed) ? 'Amanhã' : format(parsed, 'dd/MM')
    return <section key={date} aria-labelledby={`upcoming-${date}`}><h3 id={`upcoming-${date}`} className="sticky top-0 bg-white py-1 text-sm font-bold text-[#071044]">{label}</h3><ul className="mt-1 divide-y divide-[#e4edf7]">{appointments.map((item) => <li key={item.id} className="grid grid-cols-[3.5rem_1fr] gap-3 py-2 text-sm"><strong className="text-[#087cf0]">{formatTime(item.starts_at)}</strong><span><span className="font-medium text-[#071044]">{item.customer_name}</span><span className="block text-xs text-[#7182a8]">{item.service_name} · {item.professional_name}</span></span></li>)}</ul></section>
  })}</div>
}

export function AgendaPage() {
  const [date, setDate] = useState(today())
  const query = useQuery({ queryKey: ['appointments', 'agenda', date], queryFn: () => list<Appointment>(`/company/appointments/?date=${date}`) })
  const days = Array.from({ length: 7 }, (_, index) => addDays(new Date(`${date}T12:00:00`), index - 3))
  return <Page title="Agenda" description="Leitura rápida por horário, cliente e profissional."><div className="mb-5 grid grid-cols-7 gap-1 rounded-md border border-[#d8e5f4] bg-white p-1">{days.map((day) => { const value = format(day, 'yyyy-MM-dd'); return <button key={value} onClick={() => setDate(value)} className={`min-h-14 rounded px-1 text-center text-xs ${value === date ? 'bg-[#1f64b6] text-white' : 'text-[#7182a8] hover:bg-[#edf5fd]'}`}><span className="block uppercase">{format(day, 'EEE', { locale: ptBR })}</span><strong className="mt-1 block text-base">{format(day, 'd')}</strong></button> })}</div>{query.isPending && <LoadingState />}{query.isError && <Notice>{apiErrorMessage(query.error)}</Notice>}{query.data?.results.length === 0 && <EmptyState title="Nenhum horário ocupado" description="A agenda desta data está livre." />}{query.data && query.data.results.length > 0 && <div className="grid gap-2">{query.data.results.slice().reverse().map((item) => <article key={item.id} className="surface grid gap-2 p-4 sm:grid-cols-[5rem_1fr_1fr_auto] sm:items-center"><strong className="text-lg text-[#071044]">{formatTime(item.starts_at)}</strong><div><p className="font-medium text-[#071044]">{item.customer_name}</p><p className="muted text-sm">{item.service_name}</p></div><p className="text-sm text-[#43557e]">{item.professional_name}</p><StatusBadge status={item.status} /></article>)}</div>}</Page>
}

export function AppointmentsPage() {
  const client = useQueryClient(); const [filters, setFilters] = useState({ q: '', status: '', date: '' })
  const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value))
  const query = useQuery({ queryKey: ['appointments', filters], queryFn: () => list<Appointment>(`/company/appointments/?${params}`) })
  const act = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'confirm' | 'cancel' }) => api.post(`/company/appointments/${id}/${action}/`), onSuccess: () => client.invalidateQueries({ queryKey: ['appointments'] }) })
  return <Page title="Agendamentos" description="Pesquise, filtre e aja sobre estados permitidos pelo servidor."><div className="mb-5 grid gap-3 sm:grid-cols-3"><label className="relative"><span className="sr-only">Pesquisar</span><Search className="absolute left-3 top-3.5 size-4 text-[#667084]" /><input className="field pl-10" value={filters.q} onChange={(e) => setFilters({ ...filters, q: e.target.value })} placeholder="Cliente, serviço ou profissional" /></label><SelectField label="Status" hideLabel value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="">Todos os status</option><option value="WAITING_CONFIRMATION">Aguardando</option><option value="CONFIRMED">Confirmados</option><option value="CANCELLED">Cancelados</option></SelectField><Field label="Data" hideLabel type="date" value={filters.date} onChange={(e) => setFilters({ ...filters, date: e.target.value })} /></div>{query.isPending && <LoadingState />}{query.isError && <Notice>{apiErrorMessage(query.error)}</Notice>}{act.isError && <Notice>{apiErrorMessage(act.error)}</Notice>}{query.data?.results.length === 0 && <EmptyState title="Nenhum agendamento" description="Não há resultados para os filtros aplicados." />}{query.data && query.data.results.length > 0 && <AppointmentTable items={query.data.results} actions={(item) => <div className="flex flex-wrap gap-2">{item.status === 'WAITING_CONFIRMATION' && <Button variant="success" loading={act.isPending} onClick={() => act.mutate({ id: item.id, action: 'confirm' })}><Check className="size-4" /> Confirmar</Button>}{item.status !== 'CANCELLED' && <Button variant="danger" loading={act.isPending} onClick={() => act.mutate({ id: item.id, action: 'cancel' })}>Cancelar</Button>}{whatsappUrl(item.customer_whatsapp, item.whatsapp_message) && <a className="btn btn-secondary" target="_blank" rel="noopener noreferrer" href={whatsappUrl(item.customer_whatsapp, item.whatsapp_message) || undefined}>WhatsApp <ExternalLink className="size-4" /></a>}</div>} />}</Page>
}

export function ServicesPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ['services'], queryFn: () => list<Service>('/company/services/') }); const professionals = useQuery({ queryKey: ['professionals'], queryFn: () => list<Professional>('/company/professionals/') }); const [editing, setEditing] = useState<Service | null | 'new'>(null); const [remove, setRemove] = useState<Service | null>(null); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({})
  const save = useMutation({ mutationFn: ({ id, payload }: { id?: string; payload: object }) => id ? api.patch(`/company/services/${id}/`, payload) : api.post('/company/services/', payload), onSuccess: () => { client.invalidateQueries({ queryKey: ['services'] }); client.invalidateQueries({ queryKey: ['professionals'] }); setFieldErrors({}); setEditing(null) }, onError: (error) => setFieldErrors(apiFieldErrors(error)) }); const del = useMutation({ mutationFn: (id: string) => api.delete(`/company/services/${id}/`), onSuccess: () => { client.invalidateQueries({ queryKey: ['services'] }); setRemove(null) } })
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const errors = validateForm(event.currentTarget); if (Object.keys(errors).length) { setFieldErrors(errors); return } const data = new FormData(event.currentTarget); save.mutate({ id: editing !== 'new' && editing ? editing.id : undefined, payload: { name: data.get('name'), description: data.get('description'), price: data.get('price') || null, duration: minutesToDuration(Number(data.get('duration'))), slot_interval: minutesToDuration(Number(data.get('slot_interval'))), is_active: data.get('is_active') === 'on', professional_ids: data.getAll('professionals') } }) }
  return <Page title="Serviços" description="Itens que podem ser reservados na página pública." action={<Button onClick={() => setEditing('new')}><Plus className="size-4" /> Novo serviço</Button>}>{query.isPending && <LoadingState />}{query.isError && <Notice>{apiErrorMessage(query.error)}</Notice>}{query.data?.results.length === 0 && <EmptyState title="Nenhum serviço cadastrado" description="Crie o primeiro serviço para iniciar a configuração da agenda." />}{query.data && query.data.results.length > 0 && <div className="table-wrap"><table className="data-table responsive-table"><thead><tr><th>Serviço</th><th>Duração</th><th>Intervalo</th><th>Preço</th><th>Estado</th><th>Ações</th></tr></thead><tbody>{query.data.results.map((item) => <tr key={item.id}><td data-label="Serviço"><strong className="text-[#071044]">{item.name}</strong><span className="mt-1 block max-w-md truncate text-xs text-[#7182a8]">{item.description || 'Sem descrição'}</span></td><td data-label="Duração">{durationMinutes(item.duration)} min</td><td data-label="Intervalo">{durationMinutes(item.slot_interval)} min</td><td data-label="Preço">{formatMoney(item.price) || 'Não informado'}</td><td data-label="Estado">{item.is_active ? 'Ativo' : 'Inativo'}</td><td data-label="Ações"><div className="flex gap-2"><Button variant="ghost" aria-label={`Editar ${item.name}`} onClick={() => setEditing(item)}><Pencil className="size-4" /></Button><Button variant="ghost" aria-label={`Excluir ${item.name}`} onClick={() => setRemove(item)}><Trash2 className="size-4" /></Button></div></td></tr>)}</tbody></table></div>}
    <Dialog open={Boolean(editing)} title={editing === 'new' ? 'Novo serviço' : 'Editar serviço'} onClose={() => { setFieldErrors({}); setEditing(null) }}><form className="grid gap-4" onSubmit={submit} noValidate><Field label="Nome" name="name" defaultValue={editing !== 'new' && editing ? editing.name : ''} required maxLength={120} error={fieldErrors.name} /><TextAreaField label="Descrição" name="description" defaultValue={editing !== 'new' && editing ? editing.description : ''} maxLength={2000} /><div className="grid gap-3 sm:grid-cols-3"><Field label="Duração (min)" name="duration" type="number" min={5} max={1440} defaultValue={editing !== 'new' && editing ? durationMinutes(editing.duration) : 30} required error={fieldErrors.duration} /><Field label="Intervalo (min)" name="slot_interval" type="number" min={5} max={1440} defaultValue={editing !== 'new' && editing ? durationMinutes(editing.slot_interval) : 30} required error={fieldErrors.slot_interval} /><Field label="Preço opcional" name="price" type="number" min={0} step="0.01" defaultValue={editing !== 'new' && editing ? editing.price || '' : ''} error={fieldErrors.price} /></div><p className="-mt-2 text-xs text-[#7182a8]">O intervalo define a distância entre os inícios dos horários deste serviço.</p><fieldset><legend className="label">Profissionais (opcional)</legend><div className="max-h-32 space-y-1 overflow-auto rounded-md border border-[#d8e5f4] p-2">{professionals.data?.results.map((person) => <label key={person.id} className="flex min-h-10 items-center gap-2"><input type="checkbox" name="professionals" value={person.id} defaultChecked={editing !== 'new' && Boolean(editing?.professional_ids?.includes(person.id))} /> {person.name}</label>)}</div>{fieldErrors.professional_ids && <p className="field-error">{fieldErrors.professional_ids}</p>}</fieldset><label className="flex min-h-11 items-center gap-2"><input name="is_active" type="checkbox" defaultChecked={editing === 'new' || Boolean(editing?.is_active)} /> Serviço ativo</label>{save.isError && <Notice>{apiErrorMessage(save.error)}</Notice>}<Button loading={save.isPending}>Salvar serviço</Button></form></Dialog>
    <Dialog open={Boolean(remove)} title="Excluir serviço" onClose={() => setRemove(null)}><p className="muted text-sm">Excluir <strong className="text-[#071044]">{remove?.name}</strong>? O servidor recusará se houver vínculos protegidos.</p>{del.isError && <div className="mt-4"><Notice>{apiErrorMessage(del.error)}</Notice></div>}<Button className="mt-6 w-full" variant="danger" onClick={() => remove && del.mutate(remove.id)}>Excluir</Button></Dialog>
  </Page>
}

export function ProfessionalsPage() {
  const client = useQueryClient(); const people = useQuery({ queryKey: ['professionals'], queryFn: () => list<Professional>('/company/professionals/') }); const services = useQuery({ queryKey: ['services'], queryFn: () => list<Service>('/company/services/') }); const schedules = useQuery({ queryKey: ['schedules'], queryFn: () => list<WorkSchedule>('/company/work-schedules/') }); const [editing, setEditing] = useState<Professional | null | 'new'>(null); const [remove, setRemove] = useState<Professional | null>(null); const [schedulePerson, setSchedulePerson] = useState<Professional | null>(null)
  const refreshSchedules = () => client.invalidateQueries({ queryKey: ['schedules'] })
  const save = useMutation({ mutationFn: ({ id, payload }: { id?: string; payload: object }) => id ? api.patch(`/company/professionals/${id}/`, payload) : api.post('/company/professionals/', payload), onSuccess: () => { client.invalidateQueries({ queryKey: ['professionals'] }); client.invalidateQueries({ queryKey: ['services'] }); setEditing(null) } }); const del = useMutation({ mutationFn: (id: string) => api.delete(`/company/professionals/${id}/`), onSuccess: () => { client.invalidateQueries({ queryKey: ['professionals'] }); setRemove(null) } }); const addSchedule = useMutation({ mutationFn: (payload: object) => api.post('/company/work-schedules/', payload), onSuccess: refreshSchedules }); const addWeekSchedule = useMutation({ mutationFn: (payload: object) => api.post('/company/work-schedules/week/', payload), onSuccess: refreshSchedules }); const deleteSchedule = useMutation({ mutationFn: (id: string) => api.delete(`/company/work-schedules/${id}/`), onSuccess: refreshSchedules })
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); save.mutate({ id: editing !== 'new' && editing ? editing.id : undefined, payload: { name: data.get('name'), is_active: data.get('is_active') === 'on', service_ids: data.getAll('services') } }) }
  const submitSchedule = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); addSchedule.mutate({ professional: schedulePerson?.id, weekday: Number(data.get('weekday')), starts_at: data.get('starts_at'), ends_at: data.get('ends_at') }); event.currentTarget.reset() }
  const submitWeekSchedule = (form: HTMLFormElement) => { if (Object.keys(validateForm(form)).length) return; const data = new FormData(form); addWeekSchedule.mutate({ professional: schedulePerson?.id, starts_at: data.get('starts_at'), ends_at: data.get('ends_at') }) }
  return <Page title="Profissionais" description="Equipe, serviços realizados e disponibilidade semanal." action={<Button onClick={() => setEditing('new')}><Plus className="size-4" /> Novo profissional</Button>}>{people.isPending && <LoadingState />}{people.isError && <Notice>{apiErrorMessage(people.error)}</Notice>}{people.data?.results.length === 0 && <EmptyState title="Nenhum profissional" description="Cadastre quem realizará os serviços da empresa." />}{people.data && <div className="grid gap-3">{people.data.results.map((person) => <article key={person.id} className="surface flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-[#071044]">{person.name}</h2><p className="muted mt-1 text-sm">{person.service_ids.length} serviço(s) · {person.is_active ? 'Ativo' : 'Inativo'}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={() => setSchedulePerson(person)}>Horários</Button><Button variant="ghost" aria-label={`Editar ${person.name}`} onClick={() => setEditing(person)}><Pencil className="size-4" /></Button><Button variant="ghost" aria-label={`Excluir ${person.name}`} onClick={() => setRemove(person)}><Trash2 className="size-4" /></Button></div></article>)}</div>}
    <Dialog open={Boolean(editing)} title={editing === 'new' ? 'Novo profissional' : 'Editar profissional'} onClose={() => setEditing(null)}><form className="grid gap-4" onSubmit={submit}><Field label="Nome" name="name" defaultValue={editing !== 'new' && editing ? editing.name : ''} required /><fieldset><legend className="label">Serviços realizados</legend><div className="max-h-40 space-y-1 overflow-auto rounded-md border border-[#272e3d] p-2">{services.data?.results.map((service) => <label key={service.id} className="flex min-h-10 items-center gap-2"><input type="checkbox" name="services" value={service.id} defaultChecked={editing !== 'new' && Boolean(editing?.service_ids.includes(service.id))} /> {service.name}</label>)}</div></fieldset><label className="flex min-h-11 items-center gap-2"><input name="is_active" type="checkbox" defaultChecked={editing === 'new' || Boolean(editing?.is_active)} /> Profissional ativo</label>{save.isError && <Notice>{apiErrorMessage(save.error)}</Notice>}<Button disabled={save.isPending}>Salvar profissional</Button></form></Dialog>
    <Dialog open={Boolean(schedulePerson)} title={`Horários de ${schedulePerson?.name || ''}`} onClose={() => setSchedulePerson(null)}><div className="max-h-44 space-y-2 overflow-auto">{schedules.data?.results.filter((item) => item.professional === schedulePerson?.id).map((item) => <div key={item.id} className="flex items-center justify-between rounded-md border border-[#d8e5f4] px-3 py-2 text-sm"><span>{weekdays[item.weekday]} · {item.starts_at.slice(0,5)}–{item.ends_at.slice(0,5)}</span><Button variant="ghost" aria-label="Remover horário" onClick={() => deleteSchedule.mutate(item.id)}><Trash2 className="size-4" /></Button></div>)}</div><form className="mt-4 grid gap-3" onSubmit={submitSchedule}><SelectField label="Dia da semana" name="weekday">{weekdays.map((day, index) => <option key={day} value={index}>{day}</option>)}</SelectField><div className="grid grid-cols-2 gap-3"><Field label="Início" name="starts_at" type="time" required /><Field label="Fim" name="ends_at" type="time" required /></div>{(addSchedule.isError || addWeekSchedule.isError) && <Notice>{apiErrorMessage(addSchedule.error || addWeekSchedule.error)}</Notice>}<div className="grid gap-2 sm:grid-cols-2"><Button disabled={addSchedule.isPending || addWeekSchedule.isPending}>Adicionar ao dia</Button><Button type="button" variant="secondary" disabled={addSchedule.isPending || addWeekSchedule.isPending} onClick={(event) => event.currentTarget.form && submitWeekSchedule(event.currentTarget.form)}>Definir horário para a semana toda</Button></div></form></Dialog>
    <Dialog open={Boolean(remove)} title="Excluir profissional" onClose={() => setRemove(null)}><p className="muted text-sm">Excluir <strong className="text-[#071044]">{remove?.name}</strong>? Agendamentos existentes permanecem protegidos.</p>{del.isError && <div className="mt-4"><Notice>{apiErrorMessage(del.error)}</Notice></div>}<Button className="mt-6 w-full" variant="danger" onClick={() => remove && del.mutate(remove.id)}>Excluir</Button></Dialog>
  </Page>
}

const weekdays = ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo']

export function CustomersPage() {
  const [search, setSearch] = useState(''); const query = useQuery({ queryKey: ['company-customers', search], queryFn: () => list<CompanyCustomer>(`/company/customers/?q=${encodeURIComponent(search)}`) })
  return <Page title="Clientes" description="Somente dados registrados em agendamentos desta empresa."><label className="relative mb-5 block max-w-md"><span className="sr-only">Pesquisar clientes</span><Search className="absolute left-3 top-3.5 size-4 text-[#667084]" /><input className="field pl-10" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nome, e-mail ou WhatsApp" /></label>{query.isPending && <LoadingState />}{query.isError && <Notice>{apiErrorMessage(query.error)}</Notice>}{query.data?.results.length === 0 && <EmptyState title="Nenhum cliente encontrado" description="Clientes aparecerão aqui depois do primeiro agendamento." />}{query.data && query.data.results.length > 0 && <div className="table-wrap"><table className="data-table responsive-table"><thead><tr><th>Cliente</th><th>Contato</th><th>Último agendamento</th><th></th></tr></thead><tbody>{query.data.results.map((customer) => { const url = whatsappUrl(customer.whatsapp, `Olá, ${customer.name}.`); return <tr key={customer.email}><td data-label="Cliente"><span className="flex items-center gap-3"><ProfileAvatar src={customer.avatar} name={customer.name} /><span><strong className="text-[#071044]">{customer.name}</strong><span className="block text-xs text-[#7182a8]">{customer.email}</span></span></span></td><td data-label="Contato">{customer.whatsapp}</td><td data-label="Último">{formatDateTime(customer.last_appointment_at)}</td><td data-label="Ação">{url && <a className="btn btn-secondary" href={url} target="_blank" rel="noopener noreferrer">Abrir WhatsApp <ExternalLink className="size-4" /></a>}</td></tr> })}</tbody></table></div>}</Page>
}

export function SettingsPage() {
  const client = useQueryClient(); const company = useQuery({ queryKey: ['company-profile'], queryFn: () => api.get<Company>('/company/profile/') }); const settings = useQuery({ queryKey: ['company-settings'], queryFn: () => api.get<BookingSettings>('/company/settings/') }); const options = useQuery({ queryKey: ['platform-config'], queryFn: () => api.get<PublicPlatformConfig>('/public/platform/'), staleTime: 3_600_000 }); const [message, setMessage] = useState(''); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}); const [city, setCity] = useState(''); const [state, setState] = useState(''); const [niche, setNiche] = useState(''); const [nicheCustom, setNicheCustom] = useState(''); const [businessType, setBusinessType] = useState(''); const [businessTypeCustom, setBusinessTypeCustom] = useState('')
  // The query is the source of truth for this editable controlled form.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (company.data) { setCity(company.data.city); setState(company.data.state); setNiche(company.data.niche); setNicheCustom(company.data.niche_custom || ''); setBusinessType(company.data.business_type); setBusinessTypeCustom(company.data.business_type_custom || '') } }, [company.data])
  const saveProfile = useMutation({ mutationFn: (payload: FormData) => api.patch('/company/profile/', payload), onSuccess: () => { client.invalidateQueries({ queryKey: ['company-profile'] }); client.invalidateQueries({ queryKey: ['company-shell'] }); setFieldErrors({}); setMessage('Dados da empresa atualizados.') }, onError: (error) => setFieldErrors(apiFieldErrors(error)) }); const saveSettings = useMutation({ mutationFn: (payload: object) => api.patch('/company/settings/', payload), onSuccess: () => { client.invalidateQueries({ queryKey: ['company-settings'] }); setMessage('Regras da agenda atualizadas.') } })
  if (company.isPending || settings.isPending || options.isPending) return <LoadingState />
  const error = company.error || settings.error || options.error; if (error) return <Notice>{apiErrorMessage(error)}</Notice>
  const companyOptions = options.data.company_options; const allowedTypes = companyOptions.business_types_by_niche?.[niche]; const businessTypes = allowedTypes ? companyOptions.business_types.filter((option) => allowedTypes.includes(option.value)) : companyOptions.business_types
  const submitProfile = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(''); const errors = validateForm(event.currentTarget); if (Object.keys(errors).length) { setFieldErrors(errors); return } const data = new FormData(event.currentTarget); data.set('city', city); data.set('state', state); data.set('niche', niche); data.set('niche_custom', niche === 'Other' ? nicheCustom : ''); data.set('business_type', businessType); data.set('business_type_custom', businessType === 'Other' ? businessTypeCustom : ''); const logo = data.get('logo'); if (logo instanceof File && logo.size === 0) data.delete('logo'); saveProfile.mutate(data) }
  const submitRules = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setMessage(''); const errors = validateForm(event.currentTarget); if (Object.keys(errors).length) { setFieldErrors(errors); return } const data = new FormData(event.currentTarget); saveSettings.mutate({ late_tolerance: minutesToDuration(Number(data.get('late_tolerance'))), minimum_change_notice: friendlyUnitToDuration(Number(data.get('minimum_change_notice')), String(data.get('minimum_change_notice_unit')) as FriendlyDurationUnit), whatsapp_waiting_message: data.get('whatsapp_waiting_message'), whatsapp_confirmed_message: data.get('whatsapp_confirmed_message'), whatsapp_cancelled_message: data.get('whatsapp_cancelled_message') }) }
  const logo = safeImageUrl(company.data.logo)
  const notice = durationToFriendlyUnit(settings.data.minimum_change_notice)
  return <Page title="Configurações" description="Dados públicos e regras usadas pela agenda.">
    {message && <div className="mb-4"><Notice kind="success">{message}</Notice></div>}
    <div className="grid gap-5 lg:grid-cols-2">
      <form className="panel grid gap-4" onSubmit={submitProfile} noValidate>
        <h2 className="text-lg font-semibold">Dados da empresa</h2>
        <div className="flex items-center gap-4 rounded-md border border-[#d8e5f4] p-3">{logo ? <img src={logo} alt={`Imagem atual de ${company.data.name}`} className="size-16 rounded-md object-cover" /> : <div className="grid size-16 place-items-center rounded-md bg-[#edf5ff] text-[#087cf0]"><ImageUp className="size-6" /></div>}<div className="min-w-0 flex-1"><Field label="Imagem pública (PNG, JPEG ou WebP; até 2 MB)" name="logo" type="file" accept="image/png,image/jpeg,image/webp" error={fieldErrors.logo} /></div></div>
        <Field label="Nome" name="name" defaultValue={company.data.name} required error={fieldErrors.name} />
        <Field label="Endereço público" name="slug" defaultValue={company.data.slug} required pattern="[a-z0-9-]+" error={fieldErrors.slug} />
        <Field label="CNPJ (opcional)" name="tax_identifier" defaultValue={company.data.tax_identifier} error={fieldErrors.tax_identifier} />
        <Field label="WhatsApp" name="whatsapp" defaultValue={company.data.whatsapp} required error={fieldErrors.whatsapp} />
        <Field label="Endereço" name="address" defaultValue={company.data.address} error={fieldErrors.address} />
        <div className="grid gap-3 sm:grid-cols-2"><CityAutocomplete city={city} state={state} states={companyOptions.states} onCityChange={setCity} onStateChange={setState} cityError={fieldErrors.city} stateError={fieldErrors.state} /></div>
        <div className="grid gap-3 sm:grid-cols-2"><SelectField label="Nicho" name="niche" value={niche} required error={fieldErrors.niche} onChange={(event) => { const next = event.target.value; setNiche(next); if (next !== 'Other') setNicheCustom(''); if (!companyOptions.business_types_by_niche?.[next]?.includes(businessType)) { setBusinessType(''); setBusinessTypeCustom('') } }}>{companyOptions.niches.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</SelectField><SelectField label="Tipo de negócio" name="business_type" value={businessType} required error={fieldErrors.business_type} onChange={(event) => { setBusinessType(event.target.value); if (event.target.value !== 'Other') setBusinessTypeCustom('') }}>{businessTypes.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</SelectField>{niche === 'Other' && <Field label="Qual nicho?" name="niche_custom" value={nicheCustom} onChange={(event) => setNicheCustom(event.target.value)} required maxLength={100} error={fieldErrors.niche_custom} />}{businessType === 'Other' && <Field label="Qual tipo de negócio?" name="business_type_custom" value={businessTypeCustom} onChange={(event) => setBusinessTypeCustom(event.target.value)} required maxLength={100} error={fieldErrors.business_type_custom} />}</div>
        <TextAreaField label="Observações para o cliente (opcional)" name="public_notes" defaultValue={company.data.public_notes} maxLength={4000} />
        {saveProfile.isError && <Notice>{apiErrorMessage(saveProfile.error)}</Notice>}
        <Button loading={saveProfile.isPending}>Salvar empresa</Button>
      </form>
      <form className="panel grid content-start gap-4" onSubmit={submitRules} noValidate>
        <h2 className="text-lg font-semibold">Regras da agenda</h2>
        <Field label="Tolerância de atraso (min)" name="late_tolerance" type="number" min={0} max={1440} defaultValue={durationMinutes(settings.data.late_tolerance)} required />
        <p className="-mt-2 text-xs text-[#7182a8]">Referência operacional para a equipe.</p>
        <fieldset><legend className="label">Prazo mínimo para cancelamento</legend><div className="grid grid-cols-[minmax(0,1fr)_8rem] gap-2"><input aria-label="Valor do prazo mínimo" className="field" name="minimum_change_notice" type="number" min={0} max={8760} step="0.5" defaultValue={notice.value} required /><select aria-label="Unidade do prazo mínimo" className="field" name="minimum_change_notice_unit" defaultValue={notice.unit}><option value="hours">horas</option><option value="days">dias</option></select></div></fieldset>
        <p className="-mt-2 text-xs text-[#7182a8]">Até quanto tempo antes do horário o cliente poderá cancelar ou reagendar.</p>
        <div className="mt-2 border-t border-[#d8e5f4] pt-5"><h2 className="text-lg font-semibold">Mensagens de WhatsApp</h2><p className="mt-1 text-xs leading-5 text-[#7182a8]">Placeholders: {'{cliente}'}, {'{empresa}'}, {'{servico}'}, {'{profissional}'}, {'{data}'} e {'{hora}'}. Campos vazios usam a mensagem padrão.</p></div>
        <TextAreaField label="Aguardando confirmação" name="whatsapp_waiting_message" defaultValue={settings.data.whatsapp_waiting_message} maxLength={1000} />
        <TextAreaField label="Agendamento confirmado" name="whatsapp_confirmed_message" defaultValue={settings.data.whatsapp_confirmed_message} maxLength={1000} />
        <TextAreaField label="Agendamento cancelado" name="whatsapp_cancelled_message" defaultValue={settings.data.whatsapp_cancelled_message} maxLength={1000} />
        {saveSettings.isError && <Notice>{apiErrorMessage(saveSettings.error)}</Notice>}
        <Button loading={saveSettings.isPending}>Salvar regras e mensagens</Button>
      </form>
    </div>
  </Page>
}

function Page({ title, description, action, children }: { title: string; description: string; action?: React.ReactNode; children: React.ReactNode }) { return <div>{title !== 'Visão geral' && <Link to="/admin" className="btn btn-ghost mb-3 !size-11 !p-0" aria-label="Voltar ao painel" title="Voltar"><ArrowLeft className="size-5" /></Link>}<header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="page-title">{title}</h1><p className="muted mt-2 text-sm">{description}</p></div>{action}</header>{children}</div> }
function Metric({ label, value }: { label: string; value: number }) { return <div className="panel"><p className="text-sm text-[#7182a8]">{label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-[#071044]">{value}</p></div> }
function AppointmentTable({ items, actions, compact = false }: { items: Appointment[]; actions?: (item: Appointment) => React.ReactNode; compact?: boolean }) { return <div className={compact ? '' : 'table-wrap mt-3'}><table className="data-table responsive-table"><thead><tr><th>Horário</th><th>Cliente</th><th>Serviço</th><th>Profissional</th><th>Status</th>{actions && <th>Ações</th>}</tr></thead><tbody>{items.map((item) => <tr key={item.id}><td data-label="Horário">{formatDateTime(item.starts_at)}</td><td data-label="Cliente"><span className="flex items-center gap-3"><ProfileAvatar src={item.customer_avatar} name={item.customer_name} /><span><strong className="text-[#071044]">{item.customer_name}</strong><span className="block text-xs text-[#7182a8]">{item.customer_whatsapp}</span></span></span></td><td data-label="Serviço">{item.service_name}</td><td data-label="Profissional">{item.professional_name}</td><td data-label="Status"><StatusBadge status={item.status} /></td>{actions && <td data-label="Ações">{actions(item)}</td>}</tr>)}</tbody></table></div> }
