# Generated by Django 5.2.17 on 2026-09-29 02:49

import django.db.models.deletion
import feedback.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0009_backfill_units'),
        ('professionals', '0006_remove_professional_unique_professional_name_per_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CLIENT', 'Cliente'), ('ADMIN', 'Comerciante/Admin'), ('PROFESSIONAL', 'Profissional')], max_length=16)),
                ('category', models.CharField(choices=[('BUG', 'Bug'), ('SUGGESTION', 'Sugestão'), ('FEATURE_REQUEST', 'Funcionalidade'), ('UX', 'Usabilidade'), ('OTHER', 'Outro')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('REVIEWING', 'Em análise'), ('PLANNED', 'Planejado'), ('IN_PROGRESS', 'Em desenvolvimento'), ('COMPLETED', 'Concluído'), ('REJECTED', 'Não planejado')], default='NEW', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=8)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('browser_version', models.CharField(blank=True, max_length=40)),
                ('operating_system', models.CharField(blank=True, max_length=80)),
                ('device_type', models.CharField(blank=True, max_length=30)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.professional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=feedback.models.private_storage, upload_to=feedback.models.attachment_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedback')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['user', '-created_at'], name='feedback_fe_user_id_3075a3_idx'),
        ),
    ]
